# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
bucket: <%= ENV['S3_BUCKET_NAME'] %>

development:
  secret_key_base: 'e584eb8aa9570bde3f75d49d327f8e7622dd9324cf2745a2337184d15aa833d0a7e58bfdbdd5437f2f59c73e919859e0466bb71239428720dce60c3f0a087eaa'
  mailgun_password: <%= ENV["MAILGUN_PASSWORD"] %>

test:
  secret_key_base: '8c1b0412424c8c91829a8bfd69aca42a6c299aaab17363f65c14ef4e963f0f5bc73b02f73be47a0810795fdc6a1f5628c2c752f0283e0b3da38eceeaa1df3b9e'
  mailgun_password: <%= ENV["MAILGUN_PASSWORD"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
