# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create(:id => 1, :password => 's3cr3tp455w0rd', :email => 'ima@wank.er', :username => 'haxor')
User.create(:id => 2, :password => 's3cr3tp455w0rd', :email => 'ima@cod.er', :username => 'bunchie')
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-1.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-2.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-3.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-4.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-5.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-6.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-7.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-8.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-9.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-10.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-11.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-12.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-13.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-14.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-15.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-16.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-17.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-18.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-19.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-20.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-21.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-22.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-23.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-24.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-25.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-26.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-27.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'test', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-28.jpg'), 'image/png'))
