# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
User.create(:id => 1, :password => 's3cr3tp455w0rd', :email => 'ima@wank.er', :username => 'maryMagdalene')
User.create(:id => 2, :password => 's3cr3tp455w0rd', :email => 'ima@cod.er', :username => 'alGore')
User.create(:id => 3, :password => 's3cr3tp455w0rd', :email => 'ima@mak.er', :username => 'terryGilliam')
User.create(:id => 4, :password => 's3cr3tp455w0rd', :email => 'ima@work.er', :username => 'pharoahSaunders')
User.create(:id => 5, :password => 's3cr3tp455w0rd', :email => 'ima@hack.er', :username => 'mahatmaGandhi')
User.create(:id => 6, :password => 's3cr3tp455w0rd', :email => 'ima@maraud.er', :username => 'nodeIsBetter')
User.create(:id => 7, :password => 's3cr3tp455w0rd', :email => 'ima@shak.er', :username => 'mauriceRavel')
Post.create(:user_id => 2, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-1.jpg'), 'image/png'))
Post.create(:user_id => 2, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-2.jpg'), 'image/png'))
Post.create(:user_id => 2, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-3.jpg'), 'image/png'))
Post.create(:user_id => 2, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-4.jpg'), 'image/png'))
Post.create(:user_id => 2, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-5.jpg'), 'image/png'))
Post.create(:user_id => 2, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-6.jpg'), 'image/png'))
Post.create(:user_id => 2, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-7.jpg'), 'image/png'))
Post.create(:user_id => 3, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-8.jpg'), 'image/png'))
Post.create(:user_id => 3, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-9.jpg'), 'image/png'))
Post.create(:user_id => 3, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-10.jpg'), 'image/png'))
Post.create(:user_id => 3, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-11.jpg'), 'image/png'))
Post.create(:user_id => 3, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-12.jpg'), 'image/png'))
Post.create(:user_id => 3, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-13.jpg'), 'image/png'))
Post.create(:user_id => 3, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-14.jpg'), 'image/png'))
Post.create(:user_id => 3, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-15.jpg'), 'image/png'))
Post.create(:user_id => 3, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-16.jpg'), 'image/png'))
Post.create(:user_id => 4, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-17.jpg'), 'image/png'))
Post.create(:user_id => 4, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-18.jpg'), 'image/png'))
Post.create(:user_id => 4, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-19.jpg'), 'image/png'))
Post.create(:user_id => 4, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-20.jpg'), 'image/png'))
Post.create(:user_id => 4, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-21.jpg'), 'image/png'))
Post.create(:user_id => 4, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-22.jpg'), 'image/png'))
Post.create(:user_id => 4, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-23.jpg'), 'image/png'))
Post.create(:user_id => 4, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-24.jpg'), 'image/png'))
Post.create(:user_id => 4, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-25.jpg'), 'image/png'))
Post.create(:user_id => 4, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-26.jpg'), 'image/png'))
Post.create(:user_id => 4, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-27.jpg'), 'image/png'))
Post.create(:user_id => 4, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-28.jpg'), 'image/png'))
Post.create(:user_id => 4, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-29.jpg'), 'image/png'))
Post.create(:user_id => 4, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-30.jpg'), 'image/png'))
Post.create(:user_id => 4, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-31.jpg'), 'image/png'))
Post.create(:user_id => 4, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-32.jpg'), 'image/png'))
Post.create(:user_id => 4, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-33.jpg'), 'image/png'))
Post.create(:user_id => 4, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-34.jpg'), 'image/png'))
Post.create(:user_id => 5, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-35.jpg'), 'image/png'))
Post.create(:user_id => 5, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-36.jpg'), 'image/png'))
Post.create(:user_id => 5, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-37.jpg'), 'image/png'))
Post.create(:user_id => 5, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-38.jpg'), 'image/png'))
Post.create(:user_id => 5, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-39.jpg'), 'image/png'))
Post.create(:user_id => 5, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-40.jpg'), 'image/png'))
Post.create(:user_id => 5, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-41.jpg'), 'image/png'))
Post.create(:user_id => 6, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-42.jpg'), 'image/png'))
Post.create(:user_id => 6, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-43.jpg'), 'image/png'))
Post.create(:user_id => 6, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-44.jpg'), 'image/png'))
Post.create(:user_id => 6, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-45.jpg'), 'image/png'))
Post.create(:user_id => 6, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-46.jpg'), 'image/png'))
Post.create(:user_id => 6, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-47.jpg'), 'image/png'))
Post.create(:user_id => 6, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-48.jpg'), 'image/png'))
Post.create(:user_id => 6, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-49.jpg'), 'image/png'))
Post.create(:user_id => 6, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-50.jpg'), 'image/png'))
Post.create(:user_id => 6, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-51.jpg'), 'image/png'))
Post.create(:user_id => 7, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-52.jpg'), 'image/png'))
Post.create(:user_id => 7, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-53.jpg'), 'image/png'))
Post.create(:user_id => 7, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-54.jpg'), 'image/png'))
Post.create(:user_id => 7, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-55.jpg'), 'image/png'))
Post.create(:user_id => 7, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-56.jpg'), 'image/png'))
Post.create(:user_id => 7, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-57.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-58.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-59.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-60.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-61.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-62.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-63.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-64.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-65.jpg'), 'image/png'))
Post.create(:user_id => 1, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-66.jpg'), 'image/png'))
Post.create(:user_id => 7, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-67.jpg'), 'image/png'))
Post.create(:user_id => 7, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-68.jpg'), 'image/png'))
Post.create(:user_id => 7, :caption => 'This is a well written caption', :image => fixture_file_upload(Rails.root.join('app', 'assets', 'images', 'testimg-69.jpg'), 'image/png'))